### PR TITLE
Normalization layer was not merged

### PR DESCRIPTION
**Pull request by tdyku**
As you can see you were scaling input and appending first layer and then dropping it. I don't know if it is imporvement or redundant code.

### CODE REVIEW

**Comment by kkweon** [comment]
Thank you! 
I was not aware of this mistake.

**Comment by tdyku** [comment]
Do you think this first layer really improves accuracy of net?

**Comment by kkweon** [comment]
It was experimental, and I didn't get a noticeable difference to be honest.
I just did it because color space transformation used to be beneficial back in old days. 
But I guess there is no point in doing it with CNN since it's already good at detecting features from images.

**Comment by tdyku** [comment]
This is by far best and simplest implementation of unet in tensorflow on the internet. Haven't you thought about opens-sourcing it as more general unet network? :)

**Comment by kkweon** [comment]
Thank you, but I still see a room for improvement and the code is itself for self-reference so that I can look back some of the implementations in the future. 

So, I wrote everything in a single file because that's easier for me to look up.
Probably that is also the reason you think it's the simplest.

So, I don't really have a plan for making it a real project because
- there are already so many UNet implementations
- it will be more difficult to find what I want

I love to see the real world project if you have a plan for it though :smile:

**Comment by tdyku** [comment]
Wouldn't you mind if I make one basing on your code?

**Comment by kkweon** [comment]
Nope. My code is based on other people's ideas too. 
Plus, I love to see how others implement it.

**Pull request merged**
